### ISSUE TITLE
Investigación

### ISSUE THREAD

**Issue by JohnCubides** [BrandonCetina/SNChtBotWspIA#83]
Investigaciones varias

- [ ] #84
- [ ] #85
- [ ] Investigar api Twitter ahora X
- [ ] Investigar modelo de negocio de chatboots, agentes, conversaciones, multiagente, etc
- [ ] Documentar usos y costos de Whatsapp
- [ ] Costos Infraestructura
- [ ] Costos de anuncios
- [ ] Investigar costos Notion
